name: wine-quality-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip:
    - azureml-defaults
    - scikit-learn==1.4.0
    - pandas==2.0.0
    - numpy==1.24.0
    - joblib==1.3.0
    - inference-schema